### PR TITLE
SunSpec Workgroup Model Updates

### PR DESCRIPTION
**Pull request by dersecure**

### CODE REVIEW

**Comment by jsbosch** [comment]
I don't think we can go just adding fields like that.

**Comment by dersecure** [comment]
@jsbosch In a small subgroup we discussed adding this field to the schema to help users quickly identify points required for standards around the world (US, Poland, etc.).  SunSpec agreed that this would be a helpful expansion.  We would appreciate your view on this addition.

**Comment by jsbosch** [comment]
Won't adding a field to the schema break existing implementations?

**Comment by jsbosch** [comment]
On closer examination, I think I see that  you're only adding metadata, not
SunSpec points. Is that correct? If so, I withdraw my comments.

**Comment by dersecure** [comment]
@jsbosch Yes, this update will not change the number, type, or names of the points but provide clarification on how to use them and what standards require their implementation.

**Comment by jsbosch** [comment]
Thanks for the clarification. Wouldn't it be better to decouple the points
from the standards and have a standards implementation spec define which
fields are required? Seems like it could get cluttered otherwise.

**Pull request merged**
