### PR TITLE
Fixes for Inconsistencies in Model 201, 202, 203 and 204 

### LINKED ISSUE #21: Inconsistencies in Model 201, 202, 203 and 204
These models are all apparently related with 201 being an optional subset of the larger models.

Model 201 has these elements:
```
      <point id="PPVphAB" offset="10" type="int16" sf="V_SF" units="V" />
      <point id="PPVphBC" offset="11" type="int16" sf="V_SF" units="V" />
      <point id="PPVphCA" offset="12" type="int16" sf="V_SF" units="V" />

```

The other models have these elements:
```
      <point id="PhVphAB" offset="10" type="int16" sf="V_SF" units="V" mandatory="true" />
      <point id="PhVphBC" offset="11" type="int16" sf="V_SF" units="V" mandatory="true" />
      <point id="PhVphCA" offset="12" type="int16" sf="V_SF" units="V" mandatory="true" />
```

The strings section of models 202, 203 and 204 has definitions for "PPVphAB", etc which are not used by these models, whereas these sections do not have definitions for "PhVphAB", etc which are used by these models.

Ideally, all these models would use the same identifiers for these offsets and all have string definitions only for the strings that are actually used in the model definition.

### PR DESCRIPTION
**Pull request by silvia2019**
Inconsistencies in Model 201, 202, 203 and 204

Fix #21 

Updated models 201, 202, 203 and 204 to clean up point id values.

### CODE REVIEW

**Comment by altendky** [comment]
https://github.com/sunspec/models/issues/21 (so there's a hyperlink)

**Comment by andig** [comment]
I‘d suggest to write fix #21. That way the issue will automatically be closed when the PR gets merged. I also think that- given standard github notifications- the reporter will get notified that a PR has been attahced to his issue. He could then still verify should the issue not have been fixed once closed by merging the pr.

**Comment by silvia2019** [comment]
@andig Thank you!  I will add that now.

**Comment by andig** [comment]
BTW, I just happend to stumble across the GH docs for this topic: https://help.github.com/en/articles/closing-issues-using-keywords

**Pull request merged**
