### PR TITLE
Verify Json structure on build and add basic Java library.

### PR DESCRIPTION
**Pull request by nielsbasjes**
I need to parse and read the specification for my own (java based) project.
I also needed to do quite a few checks because the json has a few things that are different when compared to the xml format which need to be checked.

Then I realized that perhaps this code could be useful for the main project as a way of more extensively verifying if everything is valid.
With this in place on each pull request the changed json (only json) is completely loaded and verified against a few rules I wrote.

With this in place the route towards actually releasing the model (json + java code) towards maven central becomes a viable option.

For your consideration.

### CODE REVIEW

**Comment by nielsbasjes** [comment]
I was told that sunspec does not accept contributions (which is in contradition with the readme).

**Comment by andig** [comment]
The attitude is so entirely frustrating. Low quality definitions, almost zero response on issues.

**Comment by nielsbasjes** [comment]
@jsbosch In accordance with the readme on Dec 31st 2022 I sent an email to support@sunspec.org
> Hi,
> 
> I would like to contribute to https://github.com/sunspec/models and it indicates my github account name  nielsbasjes  must be registered to allow this.
> 
> How does this work?

the response was

> Hi Niels,
﻿> 
> For the Models repository we are not accepting any outside Pull Requests. Thank you for your comments, we are currently reviewing them, and we welcome any future comments.
> ﻿
> Thank you,
> Sheldon
> 
> Sheldon Crow
> [support@sunspec.org](mailto:support@sunspec.org)
> SunSpec Alliance

**Comment by nielsbasjes** [comment]
I expect all proposals/pull requests to the evaluated by the owners of this specification.
Some will be accepted, many will be rejected; that is how this works.
Here they have simply closed the door to anyone for several years (I HAVE contributed before that)

**Comment by nielsbasjes** [comment]
After their email I sent this last response on Jan 4, 2023 (which went unanswered):

> Ok, then I strongly recommend updating the readme in the project to illustrate this (and
> please include a note about the everlasting discussion around json/xml).
> I was just following the published procedure.
> Note that I do not want to provide updates to the models themselves, only to the technical
> representation of the models which has several problems.
> Like differences between the xml and json, a travis that does not work, etc.

I believe the standard must be stable and versioned.
The representation of the standard (i.e. json/xml/yaml/...) is simply software that (just like all software) has bugs and has room for improvement.

The current reality is that these bugs are not addressed and the schema version and the version of the technical representation of the schema are intertwined, making a release of the representation appear as a release of a new schema.

**Pull request closed without merging**
